### ISSUE TITLE
Docker image not working for me :/

### ISSUE THREAD

**Issue by smishcraft** [steamcache/steamcache#11]
Hi,

So im trying to set this up to play around with before I take it to use at an event but this is all I get at startup of the docker. 

And it doesnt cache anything, Could you tel me where im an going wrong?
This is a fresh install of ubuntu 16.04 with all updates done.
![image](https://cloud.githubusercontent.com/assets/5015350/22702387/71f5a0d8-ed58-11e6-8805-b9c97c49ce0e.png)

**Comment by mintopia** [comment]
There's two parts to running the cache. The first is the cache which you've ran here. The second part is you need to override DNS to make clients use the cache.

https://github.com/steamcache/steamcache#quick-explaination

There is another docker image that will do this for you, the details are here:

https://github.com/steamcache/steamcache-dns

**Comment by smishcraft** [comment]
I have pfsense dealing with the dns and it shows it going through to the server in nload as i see the request coming in.

**Comment by smishcraft** [comment]
its more it freezes up the putty session upon start

**Comment by mintopia** [comment]
You are running the container in the foreground, you want to execute it to run in the background. 

Your docker run command should be something like:

`docker run -d -v /data/cache:/data/cache --restart=always --name steamcache -p 192.168.1.219:80:80 steamcache/steamcache:latest`

You will also want to use -v to mount a storage folder on your host into the /data/cache directory inside the container, otherwise the storage will not be persistent across container restarts.

**Comment by smishcraft** [comment]
So its all running and steam downloads through the container but there is nothing in the /data/cache directory and it seems to download from steam each time.

**Comment by smishcraft** [comment]
Also cant get the watchdog.sh script to run

**Comment by smishcraft** [comment]
Got it all to work thanks for your help guys :)

**Comment by Dids** [comment]
Ran into this too, and it was apparently a permission issue. It might've been caused by creating the host-side cache directory myself, instead of allowing Docker to create it, but I fixed the directory permissions recursively, and it was smooth sailing after that.
