### ISSUE TITLE
Extend config to use proxy_cache_path with max_size

### ISSUE THREAD

**Issue by JasonRivers** [steamcache/steamcache#14]
Suggested in IRC by Kisak.
The use of this will allow us to limit the amount of disk used by the cache, nginx will remove the items used oldest when it reaches the max_size.
This should be configurable when using the docker run command as an environment variable such as CACHE_MAX_SIZE, Suggested default of 500GB

**Comment by astrolox** [comment]
The choice to use proxy_cache (these options) or proxy_store is the fundamental difference between this image (steamcache/steamcache) and the generic image (steamcache/generic).

This image does not use proxy_cache because we want to store the files on disk in the exact same format that they are presented on the steam content servers. The intention was that this can then be leveraged to allow various analysis and out of bounds maintenance.

For anyone who doesn't want the files stored in this way ... the generic image is the answer.

**Comment by astrolox** [comment]
Please reopen with more information if the intent of this issue was to create some kind of hybrid configuration.

**Comment by JasonRivers** [comment]
Yep, This I understand after our chat over the weekend, I'll report back, I'm good with this decision.
