### ISSUE TITLE
Downloading in steam stops, only seeing server-status and serverlist requests in the log

### ISSUE THREAD

**Issue by NickB1** [steamcache/steamcache#26]
When downloading through the docker cache container, downloading in steam stops after a while (stays in qeued).
When this happens I'm only seeing server-status and serverlist requests in the logs through the watchlog.sh script.
In Wireshark I can see these request being answered by the cache server.

![steamcache-log](https://user-images.githubusercontent.com/1638255/33740912-b6787fb2-dba2-11e7-8182-6ca232fc7e07.jpg)

**Comment by ekhoury2000** [comment]
Same here

**Comment by Jheguy2** [comment]
I'm having the exact same issue. All of my downloads appear to be using edge.steam.top.comcast.net no matter if I use the dns container. Have you found a solution to this problem?

**Comment by gmask** [comment]
Also experiencing this on Comcast, odd. No idea how to troubleshoot.

**Comment by JasonRivers** [comment]
This is an issue with the way that Comcast operates, It's not particularly a bad thing that they're doing, but it does inconvenience the cache systems. Please follow the issue here: https://github.com/steamcache/steamcache-dns/issues/26

We are working on a solution to auto-generate the DNS records from the data held here: https://github.com/uklans/cache-domains This way the DNS image should always be up to date with what is in the uklans/cache-domains, We have already discussed adding in the comcast steamcache dns in to the uklans table.
