### ISSUE TITLE
Can't start watchlog.sh

### ISSUE THREAD

**Issue by RasmusKallas** [steamcache/steamcache#37]
I installed steamcache with [Linus Tech Tips forum help.](https://linustechtips.com/main/topic/957518-ltt-steam-cache-setup-tutorial/)

Basically I ran the following:

```
sudo docker run \
  --restart unless-stopped -d \
  --name steam-cache \
  -v /home/USERNAME/cache/steam/data:/data/cache \
  -v /home/USERNAME/cache/steam/logs:/data/logs \
  -p 192.168.1.50:80:80 \
  steamcache/generic:latest

sudo docker run \
  --restart unless-stopped -d \
  --name steamcache-dns \
  -p 192.168.1.50:53:53/udp \
  -e UPSTREAM_DNS=1.1.1.1 \
  -e STEAMCACHE_IP=192.168.1.50 \
  steamcache/steamcache-dns:latest

docker run \
 --restart unless-stopped -d \
  --name sniproxy \
  -p 443:443 \
  steamcache/sniproxy:latest
```

How can I get watchlog.sh running? I get an error 14 (Can't open /scripts/config.sh).

**Comment by JasonRivers** [comment]
How are you running watchlog? the way to run this would be with:
```
docker exec -it steam-cache /scripts/watchlog.sh
```
Be warned though that this is good for debugging something that is wrong, but it can be a slight resource hog with heavier traffic.

**Comment by jammsen** [comment]
Does not work:
root@dockernode:~# docker exec -it cache-steam /scripts/watchlog.sh

oci runtime error: exec failed: container_linux.go:265: starting container process caused "exec: \"/scripts/watchlog.sh\": stat /scripts/watchlog.sh: no such file or directory"

**Comment by mintopia** [comment]
Your container name in your first post is `steam-cache` and you've specified `cache-steam` in your exec command.

Can you check the container name and try again?

**Comment by jammsen** [comment]
@mintopia 
root@dockernode:~# docker ps | grep steamcache
2b9832562e66        steamcache/sniproxy:latest         "sniproxy -f -c /e..."   2 days ago          Up 19 hours         0.0.0.0:443->443/tcp                                                     sniproxy
2550afb47973        steamcache/steamcache-dns:latest   "bash /scripts/boo..."   2 days ago          Up 19 hours         10.10.0.109:53->53/udp                                                   steamcache-dns
1465bbdce58f        steamcache/generic:latest          "/scripts/bootstra..."   2 days ago          Up 19 hours         10.10.0.109:80->80/tcp                                                   cache-steam
root@dockernode:~# docker exec -it cache-steam ls
bootstrap.sh
root@dockernode:~# docker exec -it cache-steam pwd
/scripts
root@dockernode:~# docker exec -it cache-steam ls /
bin      etc      media    root     scripts  tmp
data     home     mnt      run      srv      usr
dev      lib      proc     sbin     sys      var

**Comment by mintopia** [comment]
@jammsen Thanks for the pastebin output. Totally agree with the naming convention as well.

The issue is that your cache is running steamcache/generic and not steamcache/steamcache (this project). watchlog.sh isn't included as part of steamcache/generic as it's a Steam specific script.

I should have spotted that in your original docker compose!

**Comment by jammsen** [comment]
What is the difference between thoose 2 repos?

**Comment by mintopia** [comment]
steamcache/steamcache is intended only for caching Steam. It uses a mirror approach in nginx to mirror the structure of a content server. This allows you to easily identify games and manage the cache. It does not work with other services as it only caches the `depot` directory.

It has some minor drawbacks around failed downloads and if a file becomes corrupt in the cache, the Steam Client may stall and fail to download anything else for that game.

steamcache/generic is a more generic web cache for caching almost any service. It has some tweaks and improvements for various caches and does a lot of things around etags, request headers, etc. It uses a caching approach in nginx, which handles failures better, but the files are stored on disk based on cache key so it's harder to manage existing content. Because it's not Steam specific, it doesn't include the watchlog.sh script.

My preference is to use steamcache/generic for all the caching, as it's better in most cases, however steamcache/steamcache is nice for the easy management of cached files on disk.

**Comment by jammsen** [comment]
So basically, one only for steam and one for a broad width of services.
Do i need the DNS service too for the Steam only version?

**Comment by mintopia** [comment]
There's an [FAQ over in steamcache/generic](https://github.com/steamcache/generic/blob/master/faq.md#how-do-you-intercept-the-http-traffic) which explains why the DNS service is used, hopefully that'll help.

**Comment by jammsen** [comment]
I read the, but my question was about the other version, if that wasnt clear:
Do i need the DNS service too for the Steam only version? (Meaning steamcache/steamcache)

**Comment by mintopia** [comment]
You need the DNS interception for both containers. You need some method of getting the HTTP traffic to hit your cache server.
