### ISSUE TITLE
Steam cache Slower When Downloading non Cached Games.

### ISSUE THREAD

**Issue by taylorknopp** [steamcache/steamcache#44]
As the title says, I am running a steam cache and everything works except when downloading any content that is not cached the download is much slower than my actual internet speed.  I have been fighting with this for a couple weeks now and here is what I have done to be sure It's not something with my setup. I have tested using two desperate machines. The first is An ubuntu 18.04 machine running on a core i5 3570k, 12gb ddr3 ram, one 3tb sata 7200rpm hdd for boot, and 2 500gb sata2 disks in raid zero for storing the cache. I have also ried storing the cache directly on the 3tb boot disk and a 120gb Kingston sata 3 ssd, as an attempt eliminate an hdd bottle neck.  The second Machine I tried was a xen server vm running ubuttu 18.04, with 6 vcores and 4gb of ram.  I have tried following multiple guides, as well as fiddling with the internal nginx config my self to try and get it working.   The best performance I have seen so far is an average speed of about megabytes per second. When downloading form steam directly I regularly see 15 megabytes per second, some times peaking to 20.  When downloading cached games I see performance about what I would expect, up 90 megabytes per second on a single gigabit NIC.

**Comment by TheTrippyTree** [comment]
I'm having the same problem. Normally I get download speeds of 15-16MB/s without steamcache, but when downloading an uncached game with steamcache it's only 4-6MB/s. I'm using 4 SSDs in RAID for the cache and get good speeds while downloading cached games, but otherwise it really isn't acceptable. I'm running this on a dual Xeon system with 24GB of RAM. The only thing that I can think of that would be slowing it would be single threaded CPU performance, but you said you're having the same issue with an i5 which should be much better. I'll try running this on an i7 system and see if anything's different.

**Comment by taylorknopp** [comment]
@TheTrippyTree I feel like it's not a cpu issue, as in all my testing I never saw very high cpu usage, either spread across multiple cores, nor on a single core/thread. Still, won't hurt for you test it on your i7.  In the end, I have found a separate solution that suits me well enough, but am curious to keep trouble shooting this as well.

**Comment by JasonRivers** [comment]
I'm looking in to some options with these slow downs, Sometime this is CPU or memory bound, however in both of these cases I don't get the feeling that that is true.

I would say 4GB RAM isn't enough for this to be anywhere close to efficient but 12GB should be. One thing that we're looking at is increasing the thread count for NGINX, This only solves some problems, though. Cloudflare recently posted a blog about optimising NGINX for caching, and one of the things they noticed is that even with SSD there was IO wait time, This is because by default NGINX is single threaded for IO, which means if you have a single read/write that takes slightly longer than it should, everything else is in a wait. So the second thing we're looking at is to change the option to enable threaded IO in NGINX. but this will need some very good testing before we enable it in the container by default.

To start with, We'll be including these options with an experimental flag so you'll have to enable them.

I'm not sure when this work will be done, but We will accept a PR if someone else gets there before we do.

**Comment by TheTrippyTree** [comment]
@taylorknopp I just completed the testing on that i7 system as well as 2 other systems with considerably lower specs & got the same results from each of them, so I think my CPU theory is pretty much dead. Which is a shame, because I really wanted to get this to work. The only other possibility is that it has something to do with my network, since each of the computers (which all have very different specs) are providing essentially the same speeds. I...don't see what would be wrong with it though. I've gotten up to about 230MB/s on file transfers between computers.

I'll keep investigating. I've seen plenty of people across the interwebs say that steamcache works perfectly fine for them, so I must be doing something wrong somewhere.

**Comment by taylorknopp** [comment]
@TheTrippyTree keep me up to date with what you find out and will do the same. I won;t have a chance to do much testing until the weekend, so on Saturday I hope to investigate the possible fixes @JasonRivers  brought up.

**Comment by TheTrippyTree** [comment]
@JasonRivers Regarding the disk I/O wait, does that mean that the initial download speeds we're seeing are CPU/RAM limited, or is it just an issue with nginx itself? I tried running the Docker containers with 2GB allocated all the way to 20GB and the download speeds weren't really affected. I also tested this on machines with very high single-threaded performance (i7) and ones with low ST performance (Xeon) and differences were within margin of error.

For the most part, I'm just trying to figure out if the initial speeds I'm seeing are normal (and that I should be expecting reduced initial download speeds) or if there's actually something wrong with my setup. The speed of downloading cached games is fantastic. I've seen downloads peak at 90MB/s with the cache, which is awesome. Problem is the initial speeds are nearly half that of my WAN, so I have to wait twice as long for new games to download.

Whatever the case, I will definitely try that experimental flag once you get around to that.

**Comment by JasonRivers** [comment]
One of our team have been able to replicate this on his cache system, We are looking in to this but it's not as easy as "turn this option on", There has been quite a lot of discussion over the last 24 hours in our Discord regarding this matter and there's a number of things we're trying and improving. Currently we haven't been able to get to the bottom of the issue, but we have managed to improve other areas while testing this.

This is simply an update to let you know that we are working on this, but currently there's no real news.

**Comment by taylorknopp** [comment]
@JasonRivers I appreciate the update, and that your team is working on this. I'm pretty new to docker and whatnot but if there is some way I can help out with this just let me know.

**Comment by JasonRivers** [comment]
@taylorknopp @TheTrippyTree please could you send me the output of: ```lspci -nn | grep -i "ethernet"```

**Comment by TheTrippyTree** [comment]
@JasonRivers Sure! Here's the output from my main server:
06:00.0 Ethernet controller [0200]: Intel Corporation 82574L Gigabit Network Connection [8086:10d3]
07:00.0 Ethernet controller [0200]: Intel Corporation 82574L Gigabit Network Connection [8086:10d3]
Let me know if you need anything else.

**Comment by taylorknopp** [comment]
@JasonRivers the grep portion of that command wasn't working for me so i just did lspci and grabbed the Ethernet controller portion of the output.  

04:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8169 PCI Gigabit Ethernet Controller (rev 10)
05:00.0 Ethernet controller: Qualcomm Atheros AR8151 v2.0 Gigabit Ethernet (rev c0)

**Comment by madonak** [comment]
Also getting very poor speeds myself. Barely hitting 2MB/s on non-cached content. When not using the cache and going direct to Steam I easily get around 45MB/s.  Installing from the cache, I get higher speeds than non-cached, but still nowhere near my normal download speeds.

Cache is running on the following hardware:
[HPE DL380e Gen8](https://h20195.www2.hpe.com/v2/getdocument.aspx?docname=c04128166), with a [Xeon E5-2430L](https://ark.intel.com/products/64613/Intel-Xeon-Processor-E5-2430L-15M-Cache-2-00-GHz-7-20-GT-s-Intel-QPI-), 32GB of ECC RAM, and 24 HPE 500GB 7200 RPM SATA drives in RAID60 (with 2 parity groups)

RAID Controller is an HPE SmartArray P822 with a 2GB battery backed flash cache.

We have an identically configured machine at work that can easily saturate a 1gbps link whilst handling an average input/writes of around 220mbps (Also using nginx), so I know the hardware is more than capable of dealing with workload.

lspci output:
`02:00.0 Ethernet controller [0200]: Intel Corporation I350 Gigabit Network Connection [8086:1521] (rev 01)
02:00.1 Ethernet controller [0200]: Intel Corporation I350 Gigabit Network Connection [8086:1521] (rev 01)
02:00.2 Ethernet controller [0200]: Intel Corporation I350 Gigabit Network Connection [8086:1521] (rev 01)
02:00.3 Ethernet controller [0200]: Intel Corporation I350 Gigabit Network Connection [8086:1521] (rev 01)
`

Server has no issue with pulling the full 45MB/s from other sources and keeping up with the writes to disk

**Comment by wowdancing** [comment]
I have the same problem, I can only download with around 50% of my normal download speed when downloading a non-cached game. (around 4.5 Mbyte per sec.). I found this solution, that another software used (also running Nginx). How can we make these changes? 
"I submitted a help request in the lancache site, and it came down to a couple things. First, I needed to disable ipv6 in nginx. 2nd, I increased the proxy delay to 300s from the default of 60s, that seems to have remediated my issues."
Source: https://www.reddit.com/r/nginx/comments/3fa8og/initial_downloads_are_slow_on_my_lancache_server/

**Comment by nexusofdoom** [comment]
I did do the proxy delay to 300 still having issues with slow downloading.

**Comment by rclarsfull** [comment]
im having the same problem, how do i change the proxy delay?
Im not finding the option.

**Comment by nexusofdoom** [comment]
I did it in the nginx config for steam 

server {
    listen lancache-steam deferred default;
    server_name steam _;
    access_log /srv/lancache/logs/access/steam.log main buffer=128k flush=1m;
    access_log /srv/lancache/logs/keys/steam.log keys_uri;
    error_log /srv/lancache/logs/errors/steam.log;

    # Steam Node
    include lancache/resolver;
    location /depot/ {
        # Currently Steam uses a default expires of now, but
        # does set Cache-Control when required so just ignore
        # Expires header for now.
        proxy_bind 10.0.4.30;
        proxy_ignore_headers Expires;
        # Steam sometimes passes security parameters on the URI
        # so we cache based on just the URI excluding the query
        # string
        proxy_cache_key "$server_name$uri";
        # Use Steam cache
        proxy_cache steam;
        proxy_read_timeout 300;
        include lancache/proxy-cache;

I also added more host names to unbound

**Comment by rclarsfull** [comment]
thx for the fast respond,
but were do i find the nginx config for steam?

btw i new to unraid and linux

**Comment by nexusofdoom** [comment]
I would look in 
etc/nginx/sites-available/steamcache.conf

**Comment by rclarsfull** [comment]
i havent a dictonary calld nginx at all,
to understand you right, nginx istalld itself when i installd steamcache docker?
becaus i never installd the nginx docker, and i dont have a docker calld nginx.
thx so far for you help, but i will need some more help

**Comment by Starholme** [comment]
I'm having a similar issue on my setup. I've come across a couple threads elsewhere about Ubuntu 16.04 vs 18.04. Anybody having this issue with a 16.04 machine? Are we all using 18.04 and seeing this issue?

**Comment by mintopia** [comment]
I see it with the generic image on 16.04 but only for Steam. It's definitely an issue we're all seeing and experiencing and I haven't found a working solution yet while testing.

**Comment by hotgore** [comment]
I have tried on both 16.04 and 18.04 with the same issue.

**Comment by Ssupreme** [comment]
Hello,

my ISP speed 100/100Mbps, download speed for one client (equipped with 1TB HDD) at a time around 10MB/s. Download speed for one client at a time over cache server around 3MB/s for first download, second download around 80MB/s. I don't see any bottlenecks on server side as it's dual 480GB SSD in raid0, i5-8600, 16GB, ASRock Fatal1ty Z370 Professional Gaming i7 with 10Gbps port to 10Gbps HPE switch. Clients connected over 1Gbps lines. The most interesting thing is that when I simultaneously run downloads on 3-4 clients for first time over cache server, I am getting around 10MB/s in total!
So server can handle higher total speed for more than one client, and each client can handle good hardware limit speed! Where is a bottleneck? I am not a linux guy, i think, there are could be some nginx/docker/other connection limits or speed limits. I am from middle europe, therefore I was thinking that cache server force to download from distant servers, as for example London is farther from me than Moscow or Warsaw. Any thoughts?

**Comment by VibroAxe** [comment]
Hi guys, 

We're trying to work on this, it's definitely a known issue seen across a number of lancache projects. If anyone has a testing environment and could test out `steamcache/generic:proxy_read_timeout` for us it would be useful to know if you experience any difference (please also retry with your current steamcache/steamcache rather than previous experience)

**Comment by nexusofdoom** [comment]
Does any one know someone at steam to see what has changed?

**Comment by Ssupreme** [comment]
> Hi guys,
> 
> We're trying to work on this, it's definitely a known issue seen across a number of lancache projects. If anyone has a testing environment and could test out `steamcache/generic:proxy_read_timeout` for us it would be useful to know if you experience any difference (please also retry with your current steamcache/steamcache rather than previous experience)

I tested it on my server, it seams I got +30% performance but it is doubtful.
I found this information "Due to a bug in the Steam for Linux client it can slow down not only its own download speeds, but all DNS using network activity at the same time", solution was to install dnsmasq, I used guide [here ](https://kipiki.inoi.us/index.php/Lan_Party_Resources)to setup DNS. It didn't help either.
 Here is download speed from server without caching, around 11MB/s
![viber image 2019-02-14 21 39 38](https://user-images.githubusercontent.com/20228887/52812294-2ed71f80-30a8-11e9-93f4-0070a73db90c.jpg)
Here is download speed from client via caching server, spead around 4MB/s
![viber image 2019-02-14 21 41 18](https://user-images.githubusercontent.com/20228887/52812971-cb4df180-30a9-11e9-93a6-bd5ee9f8d1da.jpg)
At the same time here is load on server, download spee around 8MB/s
![viber image 2019-02-14 21 40 49](https://user-images.githubusercontent.com/20228887/52813029-e587cf80-30a9-11e9-861d-af6971cf7112.jpg)
It seems to me that there is double download of same content... I'll try three clients, with 3 different games, report here, if it will be helpfull.




> Does any one know someone at steam to see what has changed?

Same with battle.net

**Comment by Practiclycrp** [comment]
Hey, just adding to this in hopes of trying to help you guys solve this, when downloading from steam I notice that there's an insane amount of DNS queries going to the cache.
https://img.prccrp.org/DOiRGPdpu7.png
https://img.prccrp.org/D39kY3KY5r.png

**Comment by Ssupreme** [comment]
Well, I tried 3 clients different games at the same time via caching server and got aournd 6-7MB/s. I started to think it is something about docker itself, and I found some supporting information. So, I changed containers network from default bridge to host, nothing changed, but I was able to run server's steam client via caching server, and I got around 4MB/s, while without caching up to 11MB/s! Also network change solved total network speed, I think in bridge mode bandwidth adds up.

**Comment by VibroAxe** [comment]
So we've made a lot of progress on this in the last few days. If anyone would like to be involved in testing we would really appreciate your help. Please head over to https://github.com/steamcache/steamcache-dns/pull/69 and follow the instructions there

**Comment by VibroAxe** [comment]
Fyi @Ssupreme this is not a docker issue as it is being seen by all of the major steam caching projects both in and out of docker containers

**Comment by VibroAxe** [comment]
https://github.com/steamcache/steamcache-dns/pull/69 is now merged and closed and should solve this problem.

Please note that steamcache/steamcache is now deprecated, we recommend moving to [steamcache/monolithic](https://hub.docker.com/r/steamcache/monolithic) instead
